base/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home),
    path('verseries', views.series),
    path('pelicula/', views.pelicula),
    path('pelicula/<int:id>', views.verpelicula),
    path('serie/<int:id>', views.verserie),
    path('commentPelicula/', views.commentPelicula),
    path('commentSerie/', views.commentSerie),
    path('login/', views.inicioSesion),
    path('logout/', views.cierreSesion),
    path('registro/', views.registrar),
    path('nuevapelicula/', views.nuevapelicula),
    path('nuevaserie/', views.nuevaserie),
    path('perfil/', views.perfil),
    path('recomendacion/', views.recomendacion),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoFinalBackend/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('base.api.urls'))
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg


# Create your models here.


class Pelicula(models.Model):
    title=models.CharField(max_length=100)
    genero_box=(
        ('Accion', 'Accion'),
        ('Terror', 'Terror'),
        ('Drama', 'Drama'),
        ('Documental', 'Documental'),
        ('Comedia', 'Comedia'),
        ('Romantica', 'Romantica'),
        ('Ciencia Ficcion', 'Ciencia Ficcion'),
        ('Animada', 'Animada'),
    )
    genero = models.CharField(max_length=15, choices=genero_box)
    sinopsis = models.TextField()
    director = models.CharField(max_length=200)
    nacionalidad = models.CharField(max_length=200)
    image = models.ImageField(upload_to='base/Images/moviesPIC')
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return self.title
    def avg_ratings(self):
        return self.comments.aggregate(
            Avg('puntaje')
        )

class Serie(models.Model):
    title=models.CharField(max_length=100)
    genero_box=(
        ('Accion', 'Accion'),
        ('Terror', 'Terror'),
        ('Drama', 'Drama'),
        ('Documental', 'Documental'),
        ('Comedia', 'Comedia'),
        ('Romantica', 'Romantica'),
        ('Ciencia Ficcion', 'Ciencia Ficcion'),
        ('Animada', 'Animada'),
    )
    genero = models.CharField(max_length=15, choices=genero_box)
    sinopsis = models.TextField()
    temporadas = models.IntegerField()
    duracion = models.IntegerField()
    image = models.ImageField(upload_to='base/Images/seriesPIC')
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return self.title


class ComentarioPelicula(models.Model):
    puntaje_box=(
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    puntaje = models.IntegerField(choices=puntaje_box)
    text = models.TextField()
    updated = models.DateTimeField(auto_now = True)
    post = models.ForeignKey(Pelicula, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add = True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)


class ComentarioSerie(models.Model):
    puntaje_box=(
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    puntaje = models.IntegerField(choices=puntaje_box)
    text = models.TextField()
    updated = models.DateTimeField(auto_now = True)
    post = models.ForeignKey(Serie, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add = True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)


class Recomendacion(models.Model):
    title=models.CharField(max_length=100)
    tipo_box=(
        ('Pelicula', 'Pelicula'),
        ('Serie', 'Serie'),
    )
    tipo = models.CharField(max_length=15, choices=tipo_box)
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return self.title

templates/inicio.html
{% extends "layouts/main.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/inicio.css' %}">
    <div class="mb-5" style="background-color: #d9f0e5;">
    <div class="d-flex align-items-center" style="background-color: #d9f0e5;">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <h1 class="d-flex m-5 p-5 fw-bold" style="text-decoration: underline;">Peliculas</h1>
            </div>
            <div class="col-4 d-flex justify-content-center align-items-center">
                <i class="bi bi-arrow-right mr-2"></i><a href="/verseries">Ir a series</a>
            </div>
        </div>
    </div>    
        
    {% for p in peliculas %}
            
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/inicio.css' %}">
    
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <div class="d-flex my-4 py-4 border-bottom p-5" id="div1" style="background-image: url({{p.image.url}})">
                <h2 class="mb-4 font-weight-bold p-1">{{p.title}}</h2>
                <h4 class="mb-4 font-weight-bold p-1">Categoria: {{p.genero}}</h4>              
                <a class="btn btn-primary font-weight-bold" href="/pelicula/{{p.id}}"> Ver </a>
            </div>
        </div>
        <div class="col-4"></div>
    </div>
    {% endfor %}
    </div>
{% endblock %}

templates/inicioserie.html
{% extends "layouts/main.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/inicio.css' %}">

            <div class="mb-5" style="background-color: #d9f0e5;">
                <div class="d-flex align-items-center" style="background-color: #d9f0e5;">
                <div class="row">
                    <div class="col-4 d-flex justify-content-center align-items-center">
                        <i class="bi bi-arrow-left mr-2"></i><a href="/">Ir a Peliculas</a>
                    </div>
                    <div class="col-4">
                        <h1 class="d-flex m-5 p-5">Series</h1>
                    </div>
                    <div class="col-4">
                    </div>
                </div>
            </div>   
            
            

            {% for s in series %}
            
            {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'styles/inicio.css' %}">
    
            <div class="row">
                <div class="col-4"></div>
                <div class="col-4">
                    <div class="d-flex my-4 py-4 border-bottom p-5" id="div1" style="background-image: url({{s.image.url}});">
                        <h2 class="mb-4 font-weight-bold p-1" style="color: white">{{s.title}}</h2>
                        <h4 class="mb-4 font-weight-bold p-1">Categoria: {{s.genero}}</h4>
                
                        <a class="btn btn-primary" href="/serie/{{s.id}}"> Ver </a>
                    </div>
                </div>
                <div class="col-4"></div>
            </div>

            {% endfor %}


{% endblock %}

templates/iniciosesion.html
{% extends "layouts/main.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/iniciosesion.css' %}">

<div class="d-flex p-5">
    <div class="container d-flex p-5 justify-content-center" style="background-color: white; width: 100%; border-radius: 20px;">
        <h1 class="p-4">Iniciar Sesión</h1>
        <form class="d-flex justify-content-center" method="POST" action="" style="width: 60%; flex-direction: column;">
            {% csrf_token %}
            <div class="form-group my-3">
                <label> Usuario </label>
                <input type="text" class="form-control" name="username" placeholder="Usuario" style="width: 100%;">
            </div>
            <div class="form-group my-3">
                <label> Contraseña </label>
                <input type="password" class="form-control" name="password" placeholder="Password" style="width: 100%;">
            </div>
            <div class="d-flex justify-content-center">
                <a href="/registro">Aun no tengo cuenta</a>
            </div>
            <button class="btn btn-primary mt-3" type="submit">Inciar sesion</button>     
        </form>
    </div>
</div>


{% endblock %}

templates/nuevapelicula.html
{% extends "layouts/main.html" %}

{% block content %}



<div class="d-flex container justify-content-center">

<div class="my-5 p-5" style="border-width: 5px; border-style: solid; border-color: white; border-radius: 20px;">
<h1 style="text-decoration: underline;">Subir nueva pelicula</h1>
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    

    <div class="form-group my-3">
        <label> Titulo </label>
        <div>
            {{form.title}}
        </div>
    </div>

    <div class="form-group my-3">
        <label> Genero </label>
        <div>
            {{form.genero}}
        </div>
    </div>

    <div class="form-group my-3">
        <label> Sinopsis </label>
        <div>
            {{form.sinopsis}}
        </div>
    </div>

    <div class="form-group my-3">
        <label> Director </label>
        <div>
            {{form.director}}
        </div>
    </div>

    <div class="form-group my-3">
        <label> Nacionalidad </label>
        <div>
            {{form.nacionalidad}}
        </div>
    </div>

    <div class="form-group my-3">
        <label> Poster </label>
        <div>
            {{form.image}}
        </div>
    </div>

    <div class="form-group my-3">
        <div>
            {{form.user}}
        </div>
    </div>


    <button class="btn btn-primary" type="submit">Enviar</button>
</form>
</div>
</div>

{% endblock %}

templates/nuevaserie.html
{% extends "layouts/main.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/nuevaserie.css' %}">

<div class="d-flex container justify-content-center">

<div class="my-5 p-5" style="border-width: 5px; border-style: solid; border-color: white; border-radius: 20px;">
<h1 style="text-decoration: underline;">Subir nueva serie</h1>
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="form-group my-3">
        <label> Titulo </label>
        <div>
            {{form.title}}
        </div>
    </div>

    <div class="form-group my-3">
        <label> Genero </label>
        <div>
            {{form.genero}}
        </div>
    </div>

    <div class="form-group my-3">
        <label> Sinopsis </label>
        <div>
            {{form.sinopsis}}
        </div>
    </div>

    <div class="form-group my-3">
        <label> Temporadas </label>
        <div>
            {{form.temporadas}}
        </div>
    </div>

    <div class="form-group my-3">
        <label> Duracion </label>
        <div>
            {{form.duracion}}
        </div>
    </div>

    <div class="form-group my-3">
        <label> Poster </label>
        <div>
            {{form.image}}
        </div>
    </div>

    <div class="form-group my-3">
        <div>
            {{form.user}}
        </div>
    </div>

    <button class="btn btn-primary" type="submit">Enviar</button>
</form>
</div>
</div>

{% endblock %}

templates/perfil.html
{% extends "layouts/main.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/perfil.css' %}">

<div class="container">
    <h1 class="my-5 p-4">Mi Cuenta</h1>
    <div class="p-3 infoP">
        <h3 class="py-2">Nombre de usuario: {{user.username}}</h3>
        <h3 class="py-2">Nombre: {{user.first_name}}</h3>
        <h3 class="py-2">Apellido: {{user.last_name}}</h3>
        <h3 class="py-2">Email: {{user.email}}</h3>
    </div>
    <h1 class="my-5 p-4">Mi Comentarios</h1>

    <div>
        {% for p in comentario %}
            {% if request.user.is_authenticated and request.user == p.user %}
            <div class="mb-3">
                Pelicula: {{p.post}} - 
                El comentario es: {{p.text}} - 
                En la fecha: {{p.created}}
                <a href="/pelicula/{{p.post.id}}"> Ir </a>
            </div>
            {% endif %}   
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/recomendacionADM.html
{% extends "layouts/main.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/nuevapelicula.css' %}">

<div class="container mt-5">
<h1>Recomendaciones de usuarios</h1>

<div class="my-5">
    {% for r in recomendacion %}
        <div class="my-2 bg-dark p-2" style="color: white;">
        Titulo: {{r.title}} -
        Tipo: {{r.tipo}} - 
        Solicitud enviada el: {{r.created}} - 
        por {{r.user}}
        </div>
    {% endfor %}
</div>
</div>

{% endblock %}

templates/recomendacionUSU.html
{% extends "layouts/main.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/nuevapelicula.css' %}">

<div class="container mt-5 d-flex justify-content-center">


<div class="my-5 p-5" style="border-width: 5px; border-style: solid; border-color: white; border-radius: 20px; width: 60%;">
    <h1>Suba su recomendacion</h1>
<form method="POST" action="">
    {% csrf_token %}
    
    <div class="form-group my-5">
        <label> Titulo </label>
        <input type="text" class="form-control" name="title">
    </div>
    <div class="form-group my-5">
        <label> Tipo de Solicitud</label></br>
        <select name="tipo">
            <option value="Pelicula">Pelicula</option>
            <option value="Serie">Serie</option>
        </select>
    </div>

    <button class="btn btn-primary" type="submit">Enviar</button>
</form>
</div>
</div>

{% endblock %}

templates/registrar.html
{% extends "layouts/main.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/registrar.css' %}">

<div class="d-flex p-5">
    <div class="py-5 container d-flex" style="border-radius: 20px; background-color: white;">
        <h1 class="p-4">Registro</h1>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="form-group my-3">
                <label> Usuario </label>
                <input type="text" class="form-control" name="username" placeholder="Nombre de usuario" style="width: 700px;">
            </div>
            <div class="form-group my-3">
                <label> Email </label>
                <input type="email" class="form-control" name="email" placeholder="Email">
            </div>
            <div class="form-group my-3">
                <label> Nombre </label>
                <input type="text" class="form-control" name="name" placeholder="Nombre">
            </div>
            <div class="form-group my-3">
                <label> Apellido </label>
                <input type="text" class="form-control" name="lastname" placeholder="Apellido">
            </div>
            <div class="form-group my-3">
                <label> Contraseña </label>
                <input type="password" class="form-control" name="password" placeholder="Contraseña">
            </div>
            <div class="form-group my-3">
                <label> Confirmar Contraseña </label>
                <input type="password" class="form-control" name="confirm_password" placeholder="Confirmar Contraseña">
            </div>
            <button class="btn btn-primary" type="submit">Registrar</button>
        </form>
    </div>
</div>

{% endblock %}

templates/sincuenta.html
{% extends "layouts/main.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/sincuenta.css' %}">

<div class="d-flex justify-content-center">
<div class="d-flex mt-5" style="background-color: #d9f0e5;">
    <div class="d-flex align-items-center">
        {% load static %}
        <img src="{% static 'images/AtentionInfo.png' %}" alt="My image">
    </div>
    <div>
        <div class="divMsg p-5">
            <h1>Usted debe estar logueado poder ver el contenido :(</h1>
        </div>   
        <div class="mt-2">
            <a class="pl-5" href="/registro">Ir a crear cuenta</a>
        </div> 
    </div>
</div>
</div>

{% endblock %}

templates/verpelicula.html
{% extends "layouts/main.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/verpelicula.css' %}">

<div class="d-flex justify-content-center" style="height: auto"> 
<div class="container m-5 d-flex justify-content-center" style="flex-direction: column;">

    <div class="d-flex" id="divTitle">
        <div style="width: 75%;"><h1 class="p-5">{{pelicula.title}}</h1></div>
        <div style="width: 25%; text-align: center; align-self: center;"><h1><i class="bi bi-star mr-2"></i>{{value}}</h1></div>
    </div>
    <h3 class="py-4">Categoria: {{pelicula.genero}}</h3>
    <img src={{pelicula.image.url}}/>
    <h4 class="py-5">{{pelicula.sinopsis}}</h4>
    <h4>Director: {{pelicula.director}}</h4></br>
    </br>
    <h4>Nacionalidad del Film: {{pelicula.nacionalidad}}</h4></br>
    </br>
    <a href="/">Volver</a>

    <form method="POST" action="/commentPelicula/">
        {% csrf_token %}
        <input type='hidden' value="{{pelicula.id}}" name="pelicula">
        <div class="form-group my-3">
            <label> Puntaje: </label>
            <select name="puntaje">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>
        <div class="form-group my-3">
            <textarea class="form-control" name="text" placeholder="Escribe su critica a la pelicula.."></textarea>
        </div>
        <button class="btn btn-primary" type="submit">Enviar comentario</button>
    </form>

    <div class="mt-5">
        <h4 class="commentTitle p-2">Comentarios</h4>
        <div class="comment p-2">
        {% for c in pelicula.comentariopelicula_set.all %}
            <div>
                <p>{{c.user}} escribió: {{c.text}} - Puntaje: <span style="font-size: large;">{{c.puntaje}}</span><span class="d-flex" style="align-items: end; font-size: x-small;">{{c.created}}</span></p>
            </div>
        {% endfor %}
        </div>
    </div>

    
</div>
</div>

{% endblock %}

templates/verserie.html
{% extends "layouts/main.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/verserie.css' %}">

<div class="d-flex justify-content-center">
    <div class="container m-5 d-flex justify-content-center" style="flex-direction: column;">
    <div class="d-flex" id="divTitle">
        <div style="width: 75%;"><h1 class="p-5">{{serie.title}}</h1></div>
        <div style="width: 25%; text-align: center; align-self: center;"><h1><i class="bi bi-star mr-2"></i>{{value}}</h1></div>
    </div>
    <h3 class="py-4">Categoria: {{serie.genero}}</h3>
    <img src={{serie.image.url}}/>
    <h4 class="py-5">{{serie.sinopsis}}</h4>
    <h4 class="py-5">Temporadas: {{serie.temporadas}}</h4></br>
    </br>
    <h4>Duracion capitulos (Aprox): {{serie.duracion}}</h4></br>
    </br>
    <a href="/inicioserie">Volver</a>

    <form method="POST" action="/commentSerie/">
        {% csrf_token %}
        <input type='hidden' value="{{serie.id}}" name="serie">
        <div class="form-group my-3">
            <label> Puntaje: </label>
            <select name="puntaje">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>
        <div class="form-group my-3">
            <textarea class="form-control" name="text" placeholder="Escribe su critica a la serie.."></textarea>
        </div>
        <button class="btn btn-primary" type="submit">Enviar comentario</button>
    </form>

    <div class="mt-5">
        <h4 class="commentTitle p-2">Comentarios</h4>
        <div class="comment p-2">
        {% for c in serie.comentarioserie_set.all %}
            <div>
                <p>{{c.user}} escribió: {{c.text}} - Puntaje: <span style="font-size: large;">{{c.puntaje}}</span><span class="d-flex" style="align-items: end; font-size: x-small;">{{c.created}}</span></p>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
</div>
    
</div>

{% endblock %}